server:
  address: 127.0.0.1
  port: 9191
  servlet:
    context-path: /spring-boot-demo-new
  tomcat:
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    background-processor-delay: 30
foo:
  enabled: false
  remote-address:192.168.1.1
  username: foo
  password: 123456
  roles:
     - USER
     - ADMIN

